In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [2]:
dataset=pd.read_csv('insurance_pre.csv')

In [3]:
dataset

      age     sex     bmi  children smoker     region      charges
0      19  female  27.900         0    yes  southwest  16884.92400
1      18    male  33.770         1     no  southeast   1725.55230
2      28    male  33.000         3     no  southeast   4449.46200
3      33    male  22.705         0     no  northwest  21984.47061
4      32    male  28.880         0     no  northwest   3866.85520
...   ...     ...     ...       ...    ...        ...          ...
1333   50    male  30.970         3     no  northwest  10600.54830
1334   18  female  31.920         0     no  northeast   2205.98080
1335   18  female  36.850         0     no  southeast   1629.83350
1336   21  female  25.800         0     no  southwest   2007.94500
1337   61  female  29.070         0    yes  northwest  29141.36030

[1338 rows x 7 columns]

In [4]:
dataset=pd.get_dummies(dataset,drop_first=True)

In [5]:
dataset

,age,bmi,children,charges,sex_male,smoker_yes,region_northwest,region_southeast,region_southwest
0,19,27.900,0,16884.92400,0,1,0,0,1
1,18,33.770,1,1725.55230,1,0,0,1,0
2,28,33.000,3,4449.46200,1,0,0,1,0
3,33,22.705,0,21984.47061,1,0,1,0,0
4,32,28.880,0,3866.85520,1,0,1,0,0
...,...,...,...,...,...,...,...,...,...
1333,50,30.970,3,10600.54830,1,0,1,0,0
1334,18,31.920,0,2205.98080,0,0,0,0,0
1335,18,36.850,0,1629.83350,0,0,0,1,0
1336,21,25.800,0,2007.94500,0,0,0,0,1
1337,61,29.070,0,29141.36030,0,1,1,0,0

In [6]:
indep=dataset[['age','bmi','children','sex_male','smoker_yes']]
dep=dataset[['charges']]

In [7]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(indep, dep, test_size = 1/3, random_state = 0)

In [8]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [13]:
from sklearn.model_selection import GridSearchCV
from sklearn.tree import DecisionTreeRegressor
param_grid = {'criterion':['mse','mae','friedman_mse'],'max_features':['auto','sqrt','log2'],'splitter':['best','random']}
grid=GridSearchCV(DecisionTreeRegressor(),param_grid,refit=True,verbose=3,n_jobs=-1)
grid.fit(X_train,y_train)

Fitting 5 folds for each of 18 candidates, totalling 90 fits

D:\SUGANTHI\anaconda\lib\site-packages\sklearn\tree\_classes.py:366: FutureWarning: Criterion 'mae' was deprecated in v1.0 and will be removed in version 1.2. Use `criterion='absolute_error'` which is equivalent.
  warnings.warn(

GridSearchCV(estimator=DecisionTreeRegressor(), n_jobs=-1,
             param_grid={'criterion': ['mse', 'mae', 'friedman_mse'],
                         'max_features': ['auto', 'sqrt', 'log2'],
                         'splitter': ['best', 'random']},
             verbose=3)

In [14]:
re=grid.cv_results_

print("The R_score value for best parameter {}:".format(grid.best_params_))

The R_score value for best parameter {'criterion': 'mae', 'max_features': 'auto', 'splitter': 'random'}:

In [15]:
table=pd.DataFrame.from_dict(re)

In [16]:
table

,mean_fit_time,std_fit_time,mean_score_time,std_score_time,param_criterion,param_max_features,param_splitter,params,split0_test_score,split1_test_score,split2_test_score,split3_test_score,split4_test_score,mean_test_score,std_test_score,rank_test_score
0,0.037500,3.644384e-02,0.006249,0.007654,mse,auto,best,"{'criterion': 'mse', 'max_features': 'auto', '...",0.671834,0.487317,0.791643,0.610707,0.653956,0.643092,0.098312,4
1,0.015626,3.021056e-06,0.006249,0.007653,mse,auto,random,"{'criterion': 'mse', 'max_features': 'auto', '...",0.556404,0.621706,0.633206,0.555585,0.625500,0.598480,0.034888,11
2,0.015625,9.416779e-07,0.012500,0.006250,mse,sqrt,best,"{'criterion': 'mse', 'max_features': 'sqrt', '...",0.648823,0.523903,0.553569,0.628293,0.649591,0.600836,0.052128,10
3,0.015625,3.486459e-06,0.009376,0.007656,mse,sqrt,random,"{'criterion': 'mse', 'max_features': 'sqrt', '...",0.543802,0.543805,0.659792,0.499894,0.567101,0.562879,0.053113,17
4,0.015623,1.397425e-02,0.006251,0.007655,mse,log2,best,"{'criterion': 'mse', 'max_features': 'log2', '...",0.624784,0.625737,0.719106,0.619558,0.592321,0.636301,0.043164,5
5,0.015626,5.454734e-06,0.012500,0.006250,mse,log2,random,"{'criterion': 'mse', 'max_features': 'log2', '...",0.554809,0.678806,0.560241,0.490077,0.595036,0.575794,0.061663,14
6,0.065624,6.252004e-03,0.003125,0.006250,mae,auto,best,"{'criterion': 'mae', 'max_features': 'auto', '...",0.665525,0.566072,0.676411,0.586135,0.634825,0.625794,0.043271,7
7,0.050003,6.246901e-03,0.003125,0.006251,mae,auto,random,"{'criterion': 'mae', 'max_features': 'auto', '...",0.714993,0.587069,0.697945,0.643183,0.653328,0.659304,0.044962,1
8,0.046873,1.397804e-02,0.003125,0.006251,mae,sqrt,best,"{'criterion': 'mae', 'max_features': 'sqrt', '...",0.568272,0.606660,0.597197,0.672262,0.540604,0.596999,0.044189,12
9,0.031250,1.397553e-02,0.009374,0.007654,mae,sqrt,random,"{'criterion': 'mae', 'max_features': 'sqrt', '...",0.646889,0.433147,0.674738,0.507418,0.564647,0.565368,0.088824,16
10,0.034374,6.250382e-03,0.003125,0.006250,mae,log2,best,"{'criterion': 'mae', 'max_features': 'log2', '...",0.521984,0.600552,0.717330,0.572854,0.615655,0.605675,0.064303,9
11,0.034377,6.251740e-03,0.006250,0.007654,mae,log2,random,"{'criterion': 'mae', 'max_features': 'log2', '...",0.638860,0.562644,0.625402,0.565879,0.578468,0.594251,0.031665,13
12,0.012501,6.250263e-03,0.009374,0.007654,friedman_mse,auto,best,"{'criterion': 'friedman_mse', 'max_features': ...",0.705348,0.485825,0.738587,0.594507,0.650420,0.634938,0.089230,6
13,0.000000,0.000000e+00,0.009376,0.007655,friedman_mse,auto,random,"{'criterion': 'friedman_mse', 'max_features': ...",0.542957,0.710773,0.754138,0.469524,0.552489,0.605976,0.108061,8
14,0.009374,7.654111e-03,0.009374,0.007654,friedman_mse,sqrt,best,"{'criterion': 'friedman_mse', 'max_features': ...",0.584025,0.717014,0.689561,0.617537,0.620980,0.645823,0.049432,3
15,0.015625,1.219436e-06,0.003125,0.006251,friedman_mse,sqrt,random,"{'criterion': 'friedman_mse', 'max_features': ...",0.549489,0.589931,0.483085,0.551746,0.552651,0.545380,0.034571,18
16,0.012500,6.250167e-03,0.009375,0.007655,friedman_mse,log2,best,"{'criterion': 'friedman_mse', 'max_features': ...",0.653816,0.624797,0.733810,0.576802,0.669805,0.651806,0.051784,2
17,0.012500,6.249905e-03,0.003125,0.006250,friedman_mse,log2,random,"{'criterion': 'friedman_mse', 'max_features': ...",0.649302,0.515346,0.688478,0.568490,0.430189,0.570361,0.092587,15

In [17]:
age_input=float(input("age:"))
bmi_input=float(input("bmi:"))
children_input=float(input("children:"))
sex_male_input=int(input("sex male 0 or 1:"))
smoker_yes_input=float(input("smoker yes 0 or 1:"))

age:32
bmi:43
children:2
sex male 0 or 1:0
smoker yes 0 or 1:1

In [18]:
future_prediction=grid.predict([[age_input,bmi_input,children_input,sex_male_input,smoker_yes_input]])
print("future_prediction={}".format(future_prediction))

future_prediction=[46151.1245]